# Generated by Erlang.mk. Edit at your own risk!

src/echo_handler.erl:: /home/abedra/src/opensource/presentations/workshops/secure_code_workshop/distributed/deps/amqp_client/include/amqp_client.hrl /home/abedra/src/opensource/presentations/workshops/secure_code_workshop/distributed/deps/rabbit_common/include/rabbit.hrl /home/abedra/src/opensource/presentations/workshops/secure_code_workshop/distributed/deps/rabbit_common/include/rabbit_framing.hrl /home/abedra/src/opensource/presentations/workshops/secure_code_workshop/distributed/deps/rabbit_common/include/resource.hrl; @touch $@

COMPILE_FIRST +=
