PROJECT = distributed
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

DEPS = cowboy amqp_client
dep_cowboy_commit = 2.6.3
dep_amqp_clien = hex 3.7.13
DEP_PLUGINS = cowboy

include erlang.mk
